### ISSUE TITLE
Ubuntu 21.04 Support

### ISSUE THREAD

**Issue by tommytran732** [thiggy01/change-gdm-background#22]
Hi,

This is such an awesome script and it works really well on 20.04. Do you think you could update it to Ubuntu 21.04?

**Comment by ram02z** [comment]
@tommytran732 it does infact work! Just comment out lines 14-18.

**Comment by thiggy01** [comment]
@tommytran732, @ram02z
I'm glad you are finding this script useful.
I just added support for Hirsute Hippo. There's no need to comment any code.
