### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by 266-750Balloons** [thiggy01/change-gdm-background#24]
This is a wonderful utility, but It is unclear what a user can and can't do with the utility in the way of distributing and modifying it. For example, someone who wanted to include this in their Ubuntu-based distro might not want to include it because it lacks something like an MIT or GPL3 license.
I was hoping that a license could be added to make it clear for potential users of this script.

**Comment by thiggy01** [comment]
I don't like the restrictive nature of GPLv3. I'd rather license it under GPLv2 which is the one used by gnome.

**Comment by 266-750Balloons** [comment]
Okay. I made a commit to my pull request and replaced it with GPL2.
https://github.com/thiggy01/change-gdm-background/pull/25/commits/fdebc7bbaa7102ec63c811132a6d2b3a156def6b

**Comment by thiggy01** [comment]
Thanks for the changing the pull request.
It is merged now.
