### ISSUE TITLE
Error for this change-gdm-background

### ISSUE THREAD

**Issue by Bighoneypot** [thiggy01/change-gdm-background#26]
I try this to custom a live ubuntu iso with Cubic, but I have this error:

-rwxr-xr-x 1 root root 6281 Oct  1 15:15 change-gdm-background
root@cubic:~# nano change-gdm-background 
root@cubic:~# ./change-gdm-background /usr/share/wallpapers/myfile.jpg 
cp: cannot stat '': No such file or directory
Don't know how to handle ~
Don't know how to handle ~
cp: cannot create regular file '/tmp/gdm3-theme/theme': No such file or directory
Can't open /tmp/gdm3-theme/theme/gdm3.css: No such file or directory.
./change-gdm-background: line 149: /tmp/gdm3-theme/theme/.xml: No such file or directory
Don't know how to handle ~
./change-gdm-background: line 154: /tmp/gdm3-theme/theme/.xml: No such file or directory
./change-gdm-background: line 156: /tmp/gdm3-theme/theme/.xml: No such file or directory
Failed to open file ?/tmp/gdm3-theme/theme/.xml?: No such file or directory
mv: missing destination file operand after '/tmp/gdm3-theme/theme/gnome-shell-theme.gresource'
Try 'mv --help' for more information.
something went wrong.
mv: cannot stat '~': No such file or directory
No changes were applied.
rm: cannot remove '/tmp/gdm3-theme': No such file or directory
root@cubic:~# cd /tmp/ls      
-bash: cd: /tmp/ls: No such file or directory
root@cubic:~# cd /tmp/  
root@cubic:/tmp# ls
root@cubic:/tmp#

**Comment by thiggy01** [comment]
@Bighoneypot 
Probably, it didn't find the default Ubuntu theme gresource file. What's the code of your Ubuntu distro?

**Comment by thiggy01** [comment]
No response from question.
