### ISSUE TITLE
support for Ubuntu 21.10 (Impish Indri)

### ISSUE THREAD

**Issue by teplydat** [thiggy01/change-gdm-background#28]
Hi @thiggy01 

Thank you very much for the script! I used it in my previous ubuntu versions and it made my life easier.
Since Ubuntu 21.10 (Impish Indri) has been release, would it be possible to support that as well?

I get the following error message:
```
Sorry, this script only works with focal, groovy or hirsute distros.
```

**Comment by adefaria** [comment]
#MeToo! I recently updated to 21.10 and was just searching for a way to do this 15 minutes after you added this issue.

**Comment by thiggy01** [comment]
This was resolved with a pull request from @duckimann.

**Comment by teplydat** [comment]
Thank you very much!
